### ISSUE TITLE
Peer to Peer code review

### ISSUE THREAD

**Issue by shahira-sadat** [wayungi/leader-board#4]
Hi @wayungi 

![almost-there-almost](https://user-images.githubusercontent.com/80612925/157397398-00904e26-60ec-46cd-9510-240661c250ef.gif)
Some small suggestions: 
 - It will be better if you work on responsive design. your design is not working perfectly on the mobile screen.
 - Try to use a single key for your project API

cheers 👏 👏  and happy coding💻

**Comment by wayungi** [comment]
Thank you @shahira-sadat, the recommended changes have been implemented.
